version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lab-db
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: labwork
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/lab
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

volumes:
  pgdata: