version: '3.8'

services:
  labwork-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/labwork
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=labwork
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: